services:
  nginx:
    container_name: pokedec-${ENV_SUFFIX:-blue}-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.synology.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - default
      - pokedec-shared-net

  frontend:
    container_name: pokedec-${ENV_SUFFIX:-blue}-frontend
    image: ${DOCKERHUB_USERNAME:-pokedec}/pokedec-frontend:latest
    expose:
      - "80"
    volumes:
      - /volume1/docker/pokedec-shared/images:/usr/share/nginx/html/images
    depends_on:
      - backend
    restart: always

  backend:
    container_name: pokedec-${ENV_SUFFIX:-blue}-backend
    image: ${DOCKERHUB_USERNAME:-eugenioc}/pokedec-backend:latest
    expose:
      - "3000"
    volumes:
      - /volume1/docker/pokedec-shared/images:/frontend/public/images
    env_file:
      - .env.synology
    environment:
      - DB_HOST=pokedec-blue-green-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - NODE_ENV=production
      - APP_ENV=${APP_ENV} # Injected by deploy script (BLUE / GREEN)
      - APP_VERSION=${APP_VERSION} # Injected by deploy script
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    networks:
      - default
      - pokedec-shared-net

networks:
  pokedec-shared-net:
    external: true
