-- Populate regional property for master data (Full list from Pokebip/DEV)
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Asie' WHERE pokemon_id = 83;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Australie' WHERE pokemon_id = 115;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe' WHERE pokemon_id = 122;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique du Nord' WHERE pokemon_id = 128;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique du Nord et Amérique Centrale' WHERE pokemon_id = 214;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique Centrale et Îles Canaries' WHERE pokemon_id = 222;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe, Asie et Australie' WHERE pokemon_id = 313;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique, Afrique et Îles Canaries' WHERE pokemon_id = 314;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Inde et Asie du Sud' WHERE pokemon_id = 324;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe, Asie et Australie' WHERE pokemon_id = 335;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique et Afrique' WHERE pokemon_id = 336;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Ouest' WHERE pokemon_id = 337;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Est' WHERE pokemon_id = 338;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Afrique, Sud de l''Espagne et Îles Canaries' WHERE pokemon_id = 357;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Nouvelle-Zélande' WHERE pokemon_id = 369;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Canada, Russie et Alaska' WHERE pokemon_id = 417;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Selon la forme (Occident: Ouest, Orient: Est)' WHERE pokemon_id = 422;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Selon la forme (Occident: Ouest, Orient: Est)' WHERE pokemon_id = 423;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Sud' WHERE pokemon_id = 441;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Sud-Est des États-Unis' WHERE pokemon_id = 455;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Asie et Pacifique' WHERE pokemon_id = 480;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe, Afrique et Inde' WHERE pokemon_id = 481;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique et Groenland' WHERE pokemon_id = 482;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Asie et Pacifique' WHERE pokemon_id = 511;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Asie et Pacifique' WHERE pokemon_id = 512;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe, Moyen-Orient, Afrique et Inde' WHERE pokemon_id = 513;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe, Moyen-Orient, Afrique et Inde' WHERE pokemon_id = 514;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique et Groenland' WHERE pokemon_id = 515;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique et Groenland' WHERE pokemon_id = 516;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Amérique (Nord et Sud) et Afrique' WHERE pokemon_id = 538;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Europe, Asie et Australie' WHERE pokemon_id = 539;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Selon la couleur (Bleu: Ouest, Rouge: Est)' WHERE pokemon_id = 550;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'États-Unis (Sud), Mexique, Amérique (Centre et Sud) et Caraïbes' WHERE pokemon_id = 556;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Égypte et Grèce' WHERE pokemon_id = 561;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'New-York' WHERE pokemon_id = 626;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Est' WHERE pokemon_id = 631;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Ouest' WHERE pokemon_id = 632;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Selon la couleur (Rouge: EU/AF, Bleu: Asie-Pacifique, Jaune: Amérique)' WHERE pokemon_id = 669;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Selon la coupe (Reine: France, Kabuki: Japon, Pharaon: Égypte, etc.)' WHERE pokemon_id = 676;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Mexique' WHERE pokemon_id = 701;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'France' WHERE pokemon_id = 707;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Selon le style (Flamenco: EU/AF, Pom-Pom: Amérique, Hula: Îles, Buyō: Asie)' WHERE pokemon_id = 741;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hawaï' WHERE pokemon_id = 764;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Sud' WHERE pokemon_id = 797;
UPDATE pokemon_master SET is_regional = TRUE, regional_description = 'Hémisphère Nord' WHERE pokemon_id = 798;
